// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Ai7CNQqMlV9IoIXCbbGqVXmdhZhQj-A',
    appId: '1:580747271694:web:5e6bf1261f95a6569da65f',
    messagingSenderId: '580747271694',
    projectId: 'tollgateapp-5edab',
    authDomain: 'tollgateapp-5edab.firebaseapp.com',
    storageBucket: 'tollgateapp-5edab.firebasestorage.app',
    measurementId: 'G-DJ7TGQH7YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsFQY5HmdQRRPGp1BbEg6JVtE7XAv0KXc',
    appId: '1:580747271694:android:6b2a0da1b4aaf28d9da65f',
    messagingSenderId: '580747271694',
    projectId: 'tollgateapp-5edab',
    storageBucket: 'tollgateapp-5edab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDMGURbksxTA9kpBPAaX_8XSGZxPcN6E',
    appId: '1:580747271694:ios:7bd27bba9a0ed60a9da65f',
    messagingSenderId: '580747271694',
    projectId: 'tollgateapp-5edab',
    storageBucket: 'tollgateapp-5edab.firebasestorage.app',
    iosBundleId: 'com.example.embeddedSystemTgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDMGURbksxTA9kpBPAaX_8XSGZxPcN6E',
    appId: '1:580747271694:ios:7bd27bba9a0ed60a9da65f',
    messagingSenderId: '580747271694',
    projectId: 'tollgateapp-5edab',
    storageBucket: 'tollgateapp-5edab.firebasestorage.app',
    iosBundleId: 'com.example.embeddedSystemTgs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Ai7CNQqMlV9IoIXCbbGqVXmdhZhQj-A',
    appId: '1:580747271694:web:118e0d87bb00fb559da65f',
    messagingSenderId: '580747271694',
    projectId: 'tollgateapp-5edab',
    authDomain: 'tollgateapp-5edab.firebaseapp.com',
    storageBucket: 'tollgateapp-5edab.firebasestorage.app',
    measurementId: 'G-NQ2S3EHFWZ',
  );
}
